packages:
  all:
    compiler:: [intel@2021.6.0]
    providers:
      mpi:: [openmpi@4.1.5]
  mpi:
    buildable: False
  openmpi:
    externals:
    - spec: openmpi@4.1.5%intel@2021.6.0
      modules:
      - openmpi/4.1.5
      prefix: /lustre/opt/openmpi/4.1.5-intel-2022.2-32bit



  zip:
    externals:
    - spec: zip@3.0
      prefix: /usr
  xz:
    externals:
    - spec: xz@5.2.4
      prefix: /usr
  wget:
    externals:
    - spec: wget@1.20.3
      prefix: /usr
  texlive:
    externals:
    - spec: texlive@20190410
      prefix: /usr
  tar:
    externals:
    - spec: tar@1.30
      prefix: /usr
  sed:
    externals:
    - spec: sed@4.7
      prefix: /usr
  ruby:
    externals:
    - spec: ruby@2.7.0
      prefix: /usr
  rsync:
    externals:
    - spec: rsync@3.1.3
      prefix: /usr
  pkg-config:
    externals:
    - spec: pkg-config@0.29.1
      prefix: /usr
  perl:
    externals:
    - spec: perl@5.30.0~cpanm+shared+threads
      prefix: /usr
  openssl:
    externals:
    - spec: openssl@1.1.1f
      prefix: /usr
  openssh:
    externals:
    - spec: openssh@8.2p1
      prefix: /usr
  ncurses:
    externals:
    - spec: ncurses@6.2.20200212+symlinks+termlib abi=6
      prefix: /usr
  mysql:
    externals:
    - spec: mysql@10.3.38
      prefix: /usr
  m4:
    externals:
    - spec: m4@1.4.18
      prefix: /usr
  lustre:
    externals:
    - spec: lustre@2.15.1_24_gbaa21ca
      prefix: /usr
  libtool:
    externals:
    - spec: libtool@2.4.6
      prefix: /usr
  libfuse:
    externals:
    - spec: libfuse@2.9.9
      prefix: /usr
  krb5:
    externals:
    - spec: krb5@1.17
      prefix: /usr
  groff:
    externals:
    - spec: groff@1.22.4
      prefix: /usr
  gmake:
    externals:
    - spec: gmake@4.2.1
      prefix: /usr
  git-lfs:
    externals: []
  git:
    externals:
    - spec: git@2.25.1~tcltk
      prefix: /usr
  gettext:
    externals:
    - spec: gettext@0.19.8.1
      prefix: /usr
  gawk:
    externals:
    - spec: gawk@5.0.1
      prefix: /usr
  flex:
    externals:
    - spec: flex@2.6.4+lex
      prefix: /usr
  findutils:
    externals:
    - spec: findutils@4.7.0
      prefix: /usr
  file:
    externals:
    - spec: file@5.38
      prefix: /usr
  diffutils:
    externals:
    - spec: diffutils@3.7
      prefix: /usr
  cpio:
    externals:
    - spec: cpio@2.13
      prefix: /usr
  bzip2:
    externals:
    - spec: bzip2@1.0.8
      prefix: /usr
  bison:
    externals:
    - spec: bison@3.5.1
      prefix: /usr
  bash:
    externals:
    - spec: bash@5.0.17
      prefix: /usr
  automake:
    externals:
    - spec: automake@1.16.1
      prefix: /usr
  autoconf:
    externals:
    - spec: autoconf@2.69
      prefix: /usr
  curl:
    externals:
    - spec: curl@7.68.0+gssapi+ldap+nghttp2
      prefix: /usr
  texinfo:
    externals:
    - spec: texinfo@6.7
      prefix: /usr
  swig:
    externals:
    - spec: swig@4.0.1
      prefix: /usr
  coreutils:
    externals:
    - spec: coreutils@8.30
      prefix: /usr
  cmake:
    externals:
    - spec: cmake@3.26.2
      prefix: /usr
  meson:
    externals:
    - spec: meson@0.53.2
      prefix: /usr
  binutils:
    externals:
    - spec: binutils@2.34
      prefix: /usr
  ninja:
    externals:
    - spec: ninja@1.10.0
      prefix: /usr
